### ISSUE TITLE
Giroscope is not working on iOS 13.4.1 and 13.5

### ISSUE THREAD

**Issue by bertobh** [MozillaReality/unity-webxr-export#407]
It seems it is a common problem with new versions, where the giroscope does not update the view, also appearing in A-frame and WebVR-polyfill:
https://github.com/aframevr/aframe/issues/4542

**Comment by De-Panther** [comment]
Following your link, it was fixed in
https://github.com/immersive-web/cardboard-vr-display
and https://github.com/immersive-web/webxr-polyfill

So using updated polyfill should work.
Until we'll fix it here, you can replace `vendor/webxr-polyfill.min.js` in `webxr.js` to `https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js`

**Comment by bertobh** [comment]
Thanks for your answer!

I tried to manually download and use the updated version of the polyfill files, and also with your proposal, more direct, but it still doesn't work. Polyfill samples are not working either (https://immersive-web.github.io/webxr-samples/), but A-frame samples (https://aframe.io/aframe/examples/) are properly working after requesting access in a pop-up window. I'll try to know how to fix it.

**Comment by EngKareemHesham** [comment]
You can try this method, it worked for me : https://github.com/MozillaReality/unity-webxr-export/pull/425
